fix: use mm provider as default
0x4007/uad.ubq.fi pull request #2
Opened 2024-03-13 19:08 UTC by Keyrxng

Resolves https://github.com/pavlovcik/uad.ubq.fi/issues/1

- staking isn't displayed until the wallet is connected so it makes sense to just use the MM provider
- development needs will be forking mainnet likely although if not set the provider to localhost
- otherwise use a websocket connection

QA:
- I've spammed refresh and it won't reproduce
- Been think of how I can test it with cypress but that would need some type of UI handling if the provider(s) fail
- would benefit from `rpc-racer`

2024-03-13 19:09 UTC, Keyrxng commented
Will continue to try to reproduce but if you have any input for QA other than manual testing lmk, I'll test the deploy preview once you approve the workflow but I'm confident it's been achieved internally

2024-03-16 01:57 UTC, pavlovcik commented
> Been think of how I can test it with cypress but that would need some type of UI handling if the provider(s) fail

You can ask our in house Cypressooooor @fernandVEYRIER

2024-03-16 10:37 UTC, Keyrxng commented
What I mean is, a UI component or UI state would need built in order to display something if the provider(s) fail, similar to the work.ubq rate limit toaster

I could add the rpc-racer and display the staking stats etc without needing to connect the wallet, then swap out the `JsonRpcProvider` for a `Web3Provider` if they decide to connect their wallet?

2024-03-16 23:08 UTC, Keyrxng commented
I've spent a couple hours today on this trying to embed the rpc-handler here's where I'm at with it, I think this would be a much larger codebase change than you'd like to see with the current state of things

- embedding it into `useWeb3()` as a hook requires both versions due to how it's used throughout the codebase meaning one has storage and the other doesn't
- because of this replacing `provider` with a new fallback provider with each latency used as config option plus how often `useWeb3` is called you see a silly amount of network requests

- as an API route I was returning just the latencies and setting up a fallback/json provider, although it means no storage

- as a hook we have storage and it's visible by the lack of failed network requests but the dapp doesn't want to play ball with any provider setup that I've tried so far and unless it's the provider returned by `useProvider()` the UI just shits the bed and doesn't load the modals

<hr/>

I'll try a few non-breaking change package bumps I hope the issue lies there (wagmi v0.8 lmao), had to bring Next up to v14 it was killing me (fixed what issues appeared, still on pages router)

Is this UI being replaced by [this](https://github.com/ubiquity/ubiquity-dollar/issues/833) or is there plans to refactor this codebase or will this remain as close to as-is as possible for the forseeable?

2024-03-17 04:25 UTC, pavlovcik commented
I don't want to invest heavily into our short term UI efforts for the dApp. I think later this year I might want to break them off into simple pages (separate repos) for ease of development, or take a new approach entirely (like dynamically generated UIs based on smart contracts.)

It seems like the smallest amount of effort would be to just edit our current UI for now and let it be for the next year or so.

2024-03-17 04:27 UTC, pavlovcik commented on packages/dapp/components/lib/hooks/useWeb3.tsx
> +      provider = new WebSocketProvider("wss://ethereum-rpc.publicnode.com", 1);
I remember we had issues with the amount of requests we were making for the audit app. Maybe websockets are the solution.

2024-03-17 05:11 UTC, pavlovcik commented
First attempt the APY failed to load (not super essential but I expected that all RPC errors should be addressed)

<img width="401" alt="image" src="https://github.com/pavlovcik/uad.ubq.fi/assets/4975670/1b1956b1-80ea-4ced-b500-6d0bdefe6501">

2024-03-17 05:12 UTC, pavlovcik requested changes
Behavior is the same

2024-03-17 12:46 UTC, Keyrxng commented
> (like dynamically generated UIs based on smart contracts.)

modern wagmi simplifies the heck out of this

> It seems like the smallest amount of effort would be to just edit our current UI for now and let it be for the next year or so.

understood, I didn't think you'd be wanting extensive changes considering it's a stop-gap

Hmmm strange it never failed for me once in my 30+ attempts but I'll see a fix to this today

Silly question but are you sure that you had pulled my changes? I'm seeing `Cloudflare.eth`` in your screenshot but my changes removed that

```ts
  if (window.ethereum) {
      provider = new Web3Provider(window.ethereum);
    } else if (IS_DEV) {
      provider = new JsonRpcProvider(LOCAL_NODE_ADDRESS);
    } else {
      provider = new WebSocketProvider("wss://ethereum-rpc.publicnode.com", 1);
    }
```

Logging the provider

![image](https://github.com/pavlovcik/uad.ubq.fi/assets/106303466/b18e64d0-47c2-4c94-9e62-cc428c0f8a3e)

<hr/>

I'll add logic to handle a failed RPC regardless

2024-03-17 13:23 UTC, pavlovcik commented
I was looking at my screenshot for the build number. I set up the project again and now I'm at build https://github.com/ubiquity/ubiquity-dollar/commit/0acdf283 will need to test again.

2024-03-17 13:29 UTC, pavlovcik commented
Our CI is all broken but I think this fixes the problem. Thanks @Keyrxng

2024-03-17 13:29 UTC, merged

2024-03-17 13:36 UTC, pavlovcik commented
@rndquu looks like this also relies on the deploys please fix

2024-03-19 16:31 UTC, rndquu commented
> @rndquu looks like this also relies on the deploys please fix

Can't push a new branch to this repo, getting `permission denied` error

2024-03-20 07:25 UTC, pavlovcik commented
> > @rndquu looks like this also relies on the deploys please fix
> 
> 
> 
> Can't push a new branch to this repo, getting `permission denied` error 

Added you